config/routes.rb
Rails.application.routes.draw do

  resources :schools do
    resources :teachers
    resources :students
    resources :courses 
  end

  root 'schools#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :teacher

  has_many :students
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :teachers
  has_many :courses, through: :teachers
  has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :course
  belongs_to :school

  has_many :teachers, through: :courses
  has_many :courses, through: :school

  validates :name, presence: true
  validates :age, numericality: {
    only_integer: true,
    greater_than: 16
  }

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :school

  has_many :students, through: :courses
  has_many :courses

  validates :name, presence: true
  validates :age, numericality: {
    only_integer: true,
    greater_than: 18
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @school = School.find(params.fetch(:school_id))
    @students = @school.students
    @courses = @school.courses
  end


end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
  end

  def show
    @school = School.find(params.fetch(:id))
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @school = School.find(params.fetch(:school_id))
    @students = @school.students
    @courses = @school.courses

  end

  def show
    @teacher = School.find(params.fetch(:school_id))
    @student = Teacher.find(params.fetch(:school_id))
    @course = Student.find(params.fetch(:school_id))
    @courses = @student.courses

  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @school = School.find(params.fetch(:school_id))
    @teachers = @school.teachers
  end

  def show
    @teacher = School.find(params.fetch(:school_id))
    @student = Teacher.find(params.fetch(:school_id))
    @students = @teacher.students
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/courses/index.html.erb
<div class="container">
  <h1 class="course-title"> All the courses </h1>

    <div class="row">
      <div class="col-md-8 courses-box">
        <ol>
          <% @courses.each do |course| %>
            <li>
              <p>Course Name: <%= course.name %></p>
              <p>Course Duration: <%= course.duration%></p>
              <p><%= link_to "School", school_path(@school), class: 'btn btn-default' %></p>

            </li>
            <%end%>
        </ol>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecureSchool</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header class="navbar navbar-fixed-top navbar-inverse">
      <nav>
        <ul class="nav navbar-nav">
          <li class="home"><%= link_to "Home", schools_path %></li>
        </ul>
      </nav>
</header>

<body>
  <div class="container">

      <%= yield %>

  </div>

</body>
</html>

app/views/schools/index.html.erb
<div class="container">
  <h1 class="home-title">Schools</h1>
  <div class="row">
    <div class="col-md-8 course-box">
      <ol class="school-box">
      <% @schools.each do |school| %>
        <li >
          <p><%= school.name %></p>
          <p><%= school.location %></p>
          <p><%= school.motto %></p>
          <%= link_to "School", school_path(school), class: 'btn btn-default' %>
        </li>
        <%end%>
      </ol>
    </div>
  </div>
</div

app/views/schools/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 school-name">
        <h1 class="school-title"><%=@school.name %></h1>

          <p><%= @school.location %></p>
          <p><%= @school.motto %></p>
    </div>
  </div>
      <div class="row">
        <div class="col-md-8 school-data">
          <p>Number Students: <%= @school.students.count%></p>
          <%= link_to "Students", school_students_path(@school), class: 'btn btn-default' %>

          <p>Number of Teachers: <%= @school.teachers.count%></p>
          <%= link_to "Teachers", school_teachers_path(@school), class: 'btn btn-default' %>
          <p>Number of Courses: <%= @school.courses.count %></p>
          <%= link_to "Courses", school_courses_path(@school), class: 'btn btn-default' %>
        </div>
      </div>
</div>

app/views/students/index.html.erb
<div class="container">
  <h1 class="student-title">All the students </h1>
  <div class="row">
    <div class="col-md-8">
      <ol class="teachers-box">
          <% @students.each do |student| %>
          <li>
            <p>Name: <%= student.name %></p>
            <p>Age: <%= student.age %></p>

            <%= link_to "Courses", school_courses_path(@school), class: 'btn btn-default' %>
          </li>
            <% end %>
          </ol>
        </div>
    </div>
</div>

app/views/students/show.html.erb
<div class="container">
  <h1 class="course-title">All the Courses </h1>
    <div class="row">
      <div class="col-md-8 courses-box">
        <ol>
        <% @courses.each do |course| %>
          <li>
            <p>Course Name: <%= course.name %></p>
            <p>Course Duration: <%= course.duration %></p>
            <p><%= link_to "Student's courses", school_student_path(@teacher, student) %></p>
          </li>
          <%end%>
        </ol>
      </div>
    </div>
</div>

app/views/teachers/index.html.erb
<div class="container">
  <h1 class="course-title">All The Courses </h1>
  <div class="row">
    <div class="col-md-8">
      <ol class="courses-box">
      <% @teachers.each do |teacher| %>
        <li>
          <p><%= teacher.name %></p>
          <p>Age: <%= teacher.age %></p>
          <p>With school since: <%= teacher.hiredate %></p>
          <p><%= link_to "Teacher's Students", school_students_path(@school, teacher), class: 'btn btn-default' %></p>

        </li>
        <%end%>
      </ol>
    </div>
  </div>
</div>

app/views/teachers/show.html.erb
<div class="container">
    <h1 class="student-title"> Students of this teacher </h1>
    <div class="row">
      <div class="col-md-8 student-box">
      <ol>
      <% @students.each do |student| %>
        <li class="student-each">
          <p><%= student.name %></p>
          <p>Age: <%= student.age %></p>
          <p><%= link_to "Student's courses", school_courses_path(@courses, student), class: 'btn btn-default' %><p>

        </li>
        <%end%>
      </ol>
    </div>
  </div>
</div>